apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bootstrap
spec:
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    chart: kube-prometheus-stack
    helm:
      values: |-
        prometheus-node-exporter:
           hostRootFsMount:
             enabled: false
        prometheusOperator:
           admissionWebhooks:
             failurePolicy: Ignore
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: 57.1.1
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
