apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bootstrap
spec:
  destination:
    name: ''
    namespace: app-of-apps
    server: 'https://kubernetes.default.svc'
  source:
    path: .
    repoURL: 'https://github.com/johncosta/gitops-examples'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
